config/routes.rb
Rails.application.routes.draw do
 
  resources :itemis
 
  root to: "home#index"
 
  get "home/csalee"
  get "home/csucree"
  get "home/milkshake"
  get "home/smoothie"

  get "order/panier"
  get "order/command"
  get "order/sendmail"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itemi.rb
class Itemi < ApplicationRecord
    belongs_to :order

    before_save :set_unit_price_and_total


    def unit_price
        self[:unit_price]
    end

    private
    def set_unit_price_and_total
        self[:unit_price] = unit_price
        self[:total] = unit_price * quantity_quantity
    end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :itemis
    before_save :set_subtotal
    before_save :set_total

    # self[:total] is use to set the number of article(s).

    def subtotal_sub
        itemis.collect{|itemi| itemi.valid? ? itemi.unit_price*itemi.quantity_quantity : 0}.sum
    end
    def totalButItsTheNbOfArticles
        itemis.collect{|itemii| itemii.valid? ? itemii.quantity_quantity : 0}.sum
    end


    private

    def set_subtotal
        if subtotal_sub > 0
        self[:subtotal] = subtotal_sub
        else
        self[:subtotal] = 0
        end
    end
    def set_total
        if totalButItsTheNbOfArticles > 0
        self[:total] = totalButItsTheNbOfArticles
        else
        self[:total] = 0
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end

    def csalee
        @item_new = current_order.itemis.new
    end

    def csucree
        @item_new = current_order.itemis.new
    end

    def milkshake
        @item_new = current_order.itemis.new
    end

    def smoothie
        @item_new = current_order.itemis.new
    end
end

app/controllers/itemis_controller.rb
class ItemisController < ApplicationController

    def create
        if order_params[:content].present?
            @order = current_order
            @order.itemis.new(order_params)
            @order.save
            session[:order_id] = @order.id
            redirect_to home_csalee_path
        end
    end

    def update
        @order = current_order
        @order_item = @order.itemis.find(params[:id])
        @order_item.update_attributes(order_params)
        @order.save
        redirect_to order_panier_path
    end

    def destroy
        @order = current_order
        @order_item = @order.itemis.find(params[:id])
        @order_item.destroy
        @order.save
        redirect_to order_panier_path
    end


    private

    def order_params
        params.require(:itemi).permit(:name, :content, :unit_price, :quantity_quantity)
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

    def panier
        @each_item = current_order.itemis
    end

    def command
        @items = current_order.total
    end

    def sendmail
        if paramss[:items].to_i != 0
            MailerManagerMailer.send_command(paramss[:nomm],paramss[:prenom],paramss[:adresse],paramss[:codepostal],paramss[:ville],paramss[:telephone],paramss[:mail], paramss[:payement], current_order).deliver_now!
            sendmail_client
        else
            redirect_to root_path
        end
    end
    def sendmail_client
        MailerManagerMailer.send_client(paramss[:nomm],paramss[:prenom],paramss[:adresse],paramss[:codepostal],paramss[:ville],paramss[:telephone],paramss[:mail], paramss[:payement], current_order).deliver_now!
        @order = current_order
        @order_item = @order.itemis
        @order_item.destroy_all
        @order.save
        redirect_to root_path
    end

    def paramss
        params.permit(:nomm, :prenom, :adresse, :codepostal, :ville, :telephone, :mail, :items, :payement)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end

    
end

app/views/home/index.html.erb
<div class="container">
    <div class="row">


      <!-- Salé -->        
      <div class="col-md-6 mt-5">
        <div class="effect">
          <%= link_to home_csalee_path, class: "text", :action => 'go' do %>
            <%= image_tag("11.png", class:"image") %>      
            <div class="bg-dark bg">         
              <div class="card-body bg-primary text-center bouton">
                <h3 class="mb-0 text">
                  <p style = "font-family:Comic Sans MS">
                    <b>
                      Crêpes salées  
                    </b>
                  </p>       
                </h3>
              </div> 
            </div>               
          <% end %>  
        </div>
      </div>
      

      <!-- Sucré --> 
      <div class="col-md-6 mt-5">
        <div class="effect">
          <%= link_to home_csucree_path, class: "text", :action => 'go' do %>
            <%= image_tag("22.png", class:"image") %>      
            <div class="bg-dark bg">         
              <div class="card-body bg-primary text-center bouton">
                <h3 class="mb-0 text">
                  <p style = "font-family:Comic Sans MS">
                    <b>
                      Crêpes sucrées  
                    </b>
                  </p>       
                </h3>
              </div> 
            </div>               
          <% end %>  
        </div>
      </div>


      <!-- Milkshake --> 
      <div class="col-md-6 mt-5">
        <div class="effect">
          <%= link_to home_milkshake_path, class: "text", :action => 'go' do %>
            <%= image_tag("33.png", class:"image") %>      
            <div class="bg-dark bg">         
              <div class="card-body bg-primary text-center bouton">
                <h3 class="mb-0 text">
                  <p style = "font-family:Comic Sans MS">
                    <b>
                      Milkshake  
                    </b>
                  </p>       
                </h3>
              </div> 
            </div>               
          <% end %>  
        </div>
      </div>


      <!-- Smoothie --> 
      <div class="col-md-6 mt-5">
        <div class="effect">
          <%= link_to home_smoothie_path, class: "text", :action => 'go' do %>
            <%= image_tag("44.png", class:"image") %>      
            <div class="bg-dark bg">         
              <div class="card-body bg-primary text-center bouton">
                <h3 class="mb-0 text">
                  <p style = "font-family:Comic Sans MS">
                    <b>
                      Smoothie  
                    </b>
                  </p>       
                </h3>
              </div> 
            </div>               
          <% end %>  
        </div>
      </div>


    </div>
</div>

app/views/home/smoothie.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark py-lg-4 mb-5" id="mainNav">
  <div class="container">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mx-auto">

        <li class="nav-item px-lg-4">
          <%= link_to home_csalee_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="secHeaderTxt">    
              Crêpes salées  
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_csucree_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="secHeaderTxt">    
              Crêpes sucrées  
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_milkshake_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="secHeaderTxt">    
              Milkshake 
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_smoothie_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="activePage">    
              Smoothie  
            </h3>              
          <% end %>  
        </li>
        
      </ul>
    </div>
  </div>

  <!-- Reduce screen -->
  <div class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none">
    <div class="container">
      <ul class="navbar-nav mx-auto">

        <li class="nav-item px-lg-4">
          <%= link_to home_csalee_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="secHeaderTxt2">    
              Crêpes salées  
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_csucree_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="secHeaderTxt2">    
              Crêpes sucrées  
            </h3>              
          <% end %>  
        </li>
        
        <li class="nav-item px-lg-4">
          <%= link_to home_milkshake_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="secHeaderTxt2">    
              Milkshake 
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_smoothie_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="activePage2">    
              Smoothie  
            </h3>              
          <% end %>  
        </li>

      </ul>
    </div>
  </div>
</nav>


<!-- Contents -->
<div class="container"> 
     
  <!-- Image -->
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto mb-5"> 
    <%= image_tag("44.png", class:"activePageImage") %>          
  </div>

  <b class="text6">Smoothie : (2 fruits + lait : 3.90€)</b>

  <!-- Fruits -->
  <div class="card bg-default mt-5 py-2">    
    <div class="card-body">

      <b class="text5">Fruits: (+1€)</b>
      
      <button class="btn btn-secondary dropdown-toggle float-right" data-toggle="dropdown">
        Ingrédients
      </button>
      <div class="dropdown-menu" >
        <a class="dropdown-item">
        <button onclick="whichBase('1')">Fraise</button>
        </a>
        <a class="dropdown-item">
        <button onclick="whichBase('2')">Framboise</button>
        </a>
        <a class="dropdown-item">
        <button onclick="whichBase('3')">Mangue</button>
        </a>
        <a class="dropdown-item">
        <button onclick="whichBase('4')">Banane</button>
        </a>
        <a class="dropdown-item">
        <button onclick="whichBase('5')">Ananas</button>
        </a>
      </div>
 
      <h5 id="message5"></h5> 

      <script type="text/javascript">

        var ingredient51 = 0;
        var ingredient52 = 0;
        var ingredient53 = 0;
        var ingredient54 = 0;
        var ingredient55 = 0;
        var virgule4 = "";

        function whichBase(nb)
        {
          if (nb == "1" && ingredient51 == "0"){Total(1); ingredient51 = 1; document.getElementById("message5").innerHTML += (virgule4 + "Fraise"); virgule4 = ", "; SetIngredientsInField('5', 'Fraise');}
          if (nb == "2" && ingredient52 == "0"){Total(1); ingredient52 = 1; document.getElementById("message5").innerHTML += (virgule4 + "Framboise"); virgule4 = ", "; SetIngredientsInField('5', 'Framboise');}
          if (nb == "3" && ingredient53 == "0"){Total(1); ingredient53 = 1; document.getElementById("message5").innerHTML += (virgule4 + "Mangue"); virgule4 = ", "; SetIngredientsInField('5', 'Mangue');}
          if (nb == "4" && ingredient54 == "0"){Total(1); ingredient54 = 1; document.getElementById("message5").innerHTML += (virgule4 + "Banane"); virgule4 = ", "; SetIngredientsInField('5', 'Banane');}
          if (nb == "5" && ingredient55 == "0"){Total(1); ingredient55 = 1; document.getElementById("message5").innerHTML += (virgule4 + "Ananas"); virgule4 = ", "; SetIngredientsInField('5', 'Ananas');}
        }

      </script>

    </div>   
  </div>

  <!-- Total -->
  <div class="card bg-default mt-5 py-2">    
    <div class="card-body">

      <b id="total" class="text5">Total:</b>
      
      <button class="btn btn-primary float-right">
        <%= form_for @item_new do |f|%>
          <%= f.hidden_field :name, value: 'Smoothie' %> 
          <%= f.hidden_field :content, :id => "hiddenRating"%>
          <%= f.hidden_field :unit_price, :id => "price"%>
          <%= f.hidden_field :quantity_quantity, value: '1' %> 
          <%= f.submit "Ajouter au panier", :class => 'btnSansEffet' %>
        <% end %>
      </button>

    <script type="text/javascript">

      var euros = 1.90;

      function Total(ee)
      {
        euros += ee;       
        var num = SetDecimal(euros);
        document.getElementById("total").innerHTML = ("Total: " + num + "€");
        document.getElementById("price").value = num;
      }

    </script>

    </div>   
  </div>

</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-1 bg-dark text-white-50 mt-5">
    <div class="container text-center">
        <h3>
            <b class="rose">EAT</b> <b class="crepes">CRÊPES</b>
            &nbsp;&nbsp;&nbsp;&nbsp;
            67 Avenue Jean Jaurès <b class="rose">51100</b> <b class="crepes">Reims</b>
        </h3>
    </div>
</footer>

app/views/layouts/_top.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-0">
    <div class="container-fluid">


        <!-- Logo -->
        <div class="btn-group btn-group-justified" role="group" aria-label="...">
            <div class="btn-group effectHeader" role="group">
            <%= link_to(image_tag("logo.png"), root_path) %>   
            </div>
        </div> 


        <!-- Textes -->
        <ul class="navbar-nav mx-auto">

            <li class=" px-lg-4">
                <h1 class= "text1">  
                    Livraison & ouverture
                </h1>
                <h1 class= "text2"> 
                    Lundi, mardi, mercredi, jeudi, vendredi et samedi
                </h1>
                <h1 class= "text2"> 
                de <b> 11h30 à 23h <b class= "text3"> NON STOP </b> </b> (ouvert toute la journée)
                </h1>
                <h1 class= "text2"> 
                    Dimanche de <b> 18h à 23h </b> 
                </h1>
            </li>

            <li class=" px-lg-4">
                <h1 class= "nb1">  
                    03 51 24 38 96
                </h1>
                <h1 class= "text4"> 
                    EN CAS DE SATURATION N'HÉSITEZ PAS À NOUS RAPPELER AU <!-- 'Logo-->
                </h1>
                <h1 class= "nb2"> 
                    06 19 19 51 32
                </h1>
            </li>

        </ul>


        <!-- Panier -->
        <%= link_to order_panier_path, :class => 'linkToSansEffect', :action => 'go' do %>
            <div class="card-body bg-primary panierBouton effectHeader">
                <label>
                    <i class="fa fa-shopping-cart fa-2x panier" id="panierEuros"></i>
                </label>
                <h5 class="panier" id="panierArticles"></h5>
            </div>
        <% end %>


        <!-- Space -->
        <ul></ul>
        

    </div><!-- /.container-fluid -->
</nav>

<script type="text/javascript">

    SetPanierEuros(<%= current_order.subtotal %>);
    SetPanierArticles(<%= current_order.total %>);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteRestaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/top"%>
    <%= yield %>
  </body>

  <footer>
    <%= render "layouts/footer"%>
  </footer>
</html>

app/views/order/command.html.erb
<div class="container">
    <div class="card bg-default mt-5 py-2">    
        <div class="card-body">       
              
            <%= form_tag({controller: "order", action: "sendmail"}, {method: "get"}) do %>
                <h4> Nom : <%= text_field_tag :nomm, nil, :required => true %> </h4>
                <h4> Prénom : <%= text_field_tag :prenom, nil, :required => true %> </h4>
                <h4> Adresse : <%= text_field_tag :adresse, nil, :required => true %> </h4>
                <h4> Code postal : <%= text_field_tag :codepostal, nil, :required => true %> </h4>
                <h4> Ville : <%= text_field_tag :ville, nil, :required => true %> </h4>
                <h4> Téléphone : <%= text_field_tag :telephone, nil, :required => true %> </h4>
                <h4> Mail : <%= email_field_tag :mail, nil, :required => true %> </h4>
                <h4> Payement : <%= select_tag :payement, options_for_select([ "Carte bancaire", "Espèces" ], "Espèces") %> </h4>
                <%= hidden_field_tag :items, @items %> 
                <button class="btn btn-primary linkToSansEffect float-right">
                <%= submit_tag "Valider commande", :class => 'btnSansEffet' %>
                </button>
            <% end %>  
          
        </div>
    </div>
</div>

app/views/order/panier.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark py-lg-4 mb-5" id="mainNav">
  <div class="container">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mx-auto">

        <li class="nav-item px-lg-4">
          <%= link_to home_csalee_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="secHeaderTxt">    
              Crêpes salées  
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_csucree_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="secHeaderTxt">    
              Crêpes sucrées  
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_milkshake_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="secHeaderTxt">    
              Milkshake 
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_smoothie_path, class: "secHeaderTxt", :action => 'go' do %>
            <h3 class="secHeaderTxt">    
              Smoothie  
            </h3>              
          <% end %>  
        </li>
        
      </ul>
    </div>
  </div>

  <!-- Reduce screen -->
  <div class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none">
    <div class="container">
      <ul class="navbar-nav mx-auto">

        <li class="nav-item px-lg-4">
          <%= link_to home_csalee_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="secHeaderTxt2">    
              Crêpes salées  
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_csucree_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="secHeaderTxt2">    
              Crêpes sucrées  
            </h3>              
          <% end %>  
        </li>
        
        <li class="nav-item px-lg-4">
          <%= link_to home_milkshake_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="secHeaderTxt2">    
              Milkshake 
            </h3>              
          <% end %>  
        </li>

        <li class="nav-item px-lg-4">
          <%= link_to home_smoothie_path, class: "secHeaderTxt2", :action => 'go' do %>
            <h3 class="secHeaderTxt2">    
              Smoothie  
            </h3>              
          <% end %>  
        </li>

      </ul>
    </div>
  </div>
</nav>


<% @each_item.each do |item| %>

  <div class="container">
    <div class="card bg-default mt-5 py-2">    
      <div class="card-body">

        <b class="text5"><%= item.name %></b>
        
        <h5  class="float-right">
          <%= number_with_precision(item.unit_price, precision: 2) %> 
          € &nbsp; x &nbsp;
          <%= item.quantity_quantity %>
          &nbsp; = &nbsp;
          <%= number_with_precision(item.total, precision: 2) %> 
          €
        </h5>
              
        <h5><%= item.content %></h5>

        &nbsp;
          
        <h5 class="float-left">

        <button class="btn btn-primary linkToSansEffect">
          <%= form_for item do |f| %>
              
            <%= link_to "Supprimer article", itemi_path(item), method: :delete, :class => 'linkToSansEffect' %>

          <% end %>
        </button>

        </h5>

        <h5 class="float-right">

          <button class="btn btn-primary">
            <%= form_for item do |f| %>

              <%= f.hidden_field :item_id, :value => item.id %>
              <%= f.hidden_field :quantity_quantity, :id => "quantity" %>
              <%= f.submit "-", :class => 'btnSansEffet' %>
              
              <script type="text/javascript">
                SetQuantityDown(<%= item.quantity_quantity %>);
              </script>

            <% end %>
          </button>
        
          &nbsp; 
          <%= item.quantity_quantity %>
          &nbsp;

          <button class="btn btn-primary">
            <%= form_for item do |f| %>

              <%= f.hidden_field :item_id, :value => item.id %>
              <%= f.hidden_field :quantity_quantity, :value => (item.quantity_quantity + 1) %>
              <%= f.submit "+", :class => 'btnSansEffet' %>
              
            <% end %>
          </button>

        </h5>
          
          
      </div>
    </div>
  </div>

<% end %>


<% if @each_item.size != 0 %>
  <div class="container">
    <div class="card bg-default mt-5 py-2">    
      <div class="card-body">    
        <b class="text5"> Total = <%= number_with_precision(current_order.subtotal, precision: 2) %> € </b>             
        <button class="btn btn-primary linkToSansEffect float-right">
          <%= link_to "Commander", order_command_path, :class => 'linkToSansEffect' %>
        </button>
      </div>
    </div>
  </div>
<% end %>


<% if @each_item.size == 0 %>
  <div class="container">
    <div class="card bg-default mt-5 py-2">    
      <div class="card-body">                
        <b class="text5"> Aucun article </b> 
      </div>
    </div>
    <div class="card bg-default mt-5 py-2 invisible">    
      <div class="card-body">                
      </div>
    </div>
    <div class="card bg-default mt-5 py-2 invisible">    
      <div class="card-body">                
      </div>
    </div>
  </div>
<% end %>